### ISSUE TITLE
Nutzung der automatisierten Anzeige von Downloads: Probleme mit Layout

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/RRZE-Downloads#1]
Wäre es möglich, den Einzug in der Listendarstellung so einzustellen, dass der Text nach einem Zeilenumbruch um die Breite des PDF-Icons eingerückt ist? Das sähe wohl "ordentlicher" aus (vgl. Screenshot).
![einzug_downloads](https://cloud.githubusercontent.com/assets/12810141/8053123/e1e1ba04-0e8d-11e5-8c27-9b14d65efc8a.png)

**Comment by xwolfde** [comment]
nicht im fließtext. man muss dann schon beim format bei der liste bleiben

**Comment by FlorianFiller** [comment]
Auch durch den Zusatz format="liste" (wie in der readme.txt steht) ändert sich die Darstellung nicht.

[download category="qm" tags="downloads" format="liste"]

https://phil.cms.rrze.uni-erlangen.de/infocenter/downloadcenter/

**Comment by xwolfde** [comment]
Das liegt aber nicht an diesem Plugin. Dort wird das Mime Type Symbole Plugin verwendet, welches die Symbole macht. Wie die Symbole angezeigt werden, kann so nicht durch das Plugin beeinflusst werden.

**Comment by FlorianFiller** [comment]
Primär geht es mir ja nicht um die Symbole sondern um den Einzug nach einem Zeilenumbruch bzw. einen abweichenden Einzug der ersten Zeile - und das müsste doch an der innerhalb des PlugIns verwendeten Formatvorlage bzw. Formatierung hängen. Zumindest kann ich diese nicht beeinflussen.
Anders formuliert: format="liste" muss doch irgendwelche Auswirkungen haben.

**Comment by xwolfde** [comment]
Das Format Liste wirkt ist aussendrum. Das Symbol ist inline auf die reine Überschrift bezogen und kommt von einem anderen Plugin. 
Da haben wir keine praktikable Möglichkeit.
Empfehlung:
Titel der Dateien kürzer machen. 
Wenn eh einige z.B. "Leitfaden zur..." haben im Titek könnte man das schon weglassen und stattdessen diese Dateien in einer Kategorie "Leitfäden" tun. Das würde man als Überschrift nehmen.
