### ISSUE TITLE
Welche Dateitypen können zur Verfügung gestellt werden?

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/RRZE-Downloads#2]
Nachdem Dokumente, Audio-, Video- und Textdateien zur Verfügung gestellt werden können, wäre es sehr prächtig,  zu erfahren, welche Dateiformate heruntergeladen werden können (Grafikdateien sind ja derzeit nicht vorgesehen, beispielsweise). Oder sind einfach alle Dateitypen außer Grafiken nutzbar?

**Comment by xwolfde** [comment]
nur dateitypen aus application/*  - also keine bilder
