### ISSUE TITLE
Eigenes Format

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/RRZE-Downloads#3]
In der Readme steht, man könne die Vor- und Nachtags (nur HTML-Tags) ändern. Als Beispiel dient folgender Shortcode: 
[downloads category="downloads" format="bluber" htmlpre="dl" htmlpost="dl" htmlitempre="dd" htmlitempost="dd"]
Stehen dl und d hier als Platzhalter für diejenigen HTML-Tags, die man dann einsetzen soll? Ich benötige bitte etwas mehr Erklärung dazu.

**Comment by xwolfde** [comment]
ja. nur die tags, ohne < und >, es geht auch nur ein einziger tag
