### ISSUE TITLE
showexcerpt und showcontent

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/RRZE-Downloads#4]
Laut Readme kann man die Attribute showexcerpt="true" und showcontent="true" setzen. Beim Test liefern die mir aber nichts auf die Seite aus. Muss in dem Dokument, das zur Verfügung gestellt wird, hier etwas bestimmtes vorhanden sein? (Im Moment habe ich ausschließlich PDFs).

**Comment by xwolfde** [comment]
siehe media-lib: dort sind felder eingebbar
