### ISSUE TITLE
AND zwischen Category und Tags scheint OR zu sein

### ISSUE THREAD

**Issue by zfldev** [RRZE-Webteam/RRZE-Downloads#5]
In der Dokumentation heißt es: Kategorie durch Tags einschränken. Heißt nur wenn Download in Kategorie und Tag gleichzeitig ist sollte der Download angezeigt. 
Momentan scheint das aber eine oder Beziehung zu sein.

Danke für diese genial einfache Umsetzung einer Downloadverwaltung!

**Comment by AstridSemm** [comment]
Ich bin da sowieso gerade am Testen, von daher habe ich's mal schnell nachgeguckt - bei mir tut es fabelhaft. Wo tritt das unerwünschte Verhalten in welcher Form mit was für Kategorien, Schlagwörtern und shortcode auf?

**Comment by zfldev** [comment]
OK, kann bestätigen es funktioniert. Das Problem besteht nur wenn die Kategorie welche im Shortcode verwendet wird noch nicht existiert.

**Comment by AstridSemm** [comment]
Ja, ok, darauf sollte man dann achten. Ich schließe den issue dann.

**Comment by zfldev** [comment]
Behoben ist der Fehler ja eigentlich noch nicht, nur erkannt.

**Comment by xwolfde** [comment]
Ähm, das war kein Fehler, das hab ich absichtlich so gemacht...

**Comment by zfldev** [comment]
Die geänderte Fehlerbeschreibung war irreführend, sorry. Es geht darum, dass wenn der Shortcode das Attribut category="wetter" und tags="wolken" beinhaltet. Die Kategorie Wetter jedoch noch nicht angelegt wurde alle Downloads mit Schlagwort wolken ausgegeben werden. Das sollte meiner Meinung nach so eigentlich nicht sein. Denn die Kategorie ist doch eigentliche die Grundvoraussetzung. Also AND zwischen Category und Tags und OR zwischen den Tags.

**Comment by xwolfde** [comment]
Nein, eben nicht.
Es soll ja möglich sein, Downloads allein anhand der Tags zu machen: Es gibt einige Anwendungsfälle, in denen nur übergreifend nach Tags gesucht werden soll und die Kategorien egal sind.
Wenn die Kategorie also leer ist oder ungültig, wird dann nur noch nach den Tags geschaut.
