### ISSUE TITLE
Category="downloads"??

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/RRZE-Downloads#7]
Wieso ist denn zur Anzeige von Dowloads mit dem Shortcode Downloads als Katgeorie anzugeben?
Dass Downloads angezeigt werden sollen, erreicht man doch bereits über den Shortcodebeginn "downloads". [downloads category=downloads] Ist das nicht eine gewisse Redundanz?

**Comment by xwolfde** [comment]
Das jemand die Kategory "Downloads" macht ist doch selbst bestimmt. Das kann ich vorher nicht wissen.
Das Argument kann man auf jeden Shortcode anwenden. Z.B. bei Kontakte die Kategory kontakte anlegen. dann hast du dort aucgh [kontakt cat="kontakte" ] ;)
